github:
  - unifiedjs
  - JounQin
  - 1stG
  - rx-ts
  - un-ts
  - unrs
patreon: 1stG
open_collective: unified
custom:
  - https://opencollective.com/1stG
  - https://opencollective.com/rxts
  - https://opencollective.com/unrs
  - https://opencollective.com/unts
  - https://afdian.com/a/JounQin
